platform :ios, '13.0'

target 'Runner' do
  use_frameworks!
  
  # Add all your pods here
  pod 'shared_preferences'
  
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
